name: CI Workflow

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Check formatting with clang-format
        run: |
          find src tests -name "*.cpp" -o -name "*.hpp" | xargs clang-format --dry-run -Werror

   build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Install dependencies (Eigen3, yaml-cpp, Boost)
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libeigen3-dev \
            libyaml-cpp-dev \
            libboost-all-dev

      # Set up CMake and build
      - name: Set up CMake and Build
        run: |
          mkdir -p build
          cd build
          cmake ..
          cmake --build .

      # Run tests after build
      - name: Run Tests
        run: |
          cd build
          ctest --output-on-failure